### PR TITLE
Fix Cheapino v2 Code

### PR DESCRIPTION
**Pull request by fauh45**
Updated the pin, and the key mapping so it works on the v2 board. Also update the encoder handler, such that it function as it should be.

## Description

So the KiCad schematic nets didn't really fit what is happening IRL (at least in my board), the right side pin order is reversed. So I just match up the left RJ45 connection to the right. See below,

image

So in this pin mapping for the right side, R_COL_1 is actually connected to R_ROW_4, R_COL_2 is connected to R_ROW_3, and as follows. The key mapping itself I just follow the schematic.

As for the encoder implementation is purely based on observation made by looking at debug data as I press all the button (see details of it in the [cheapino issue](https://github.com/tompi/cheapino/issues/17#issuecomment-1848436478))

This changes is already tested in my v2 build.

## Types of Changes

- [ ] Core
- [x] Bugfix
- [x] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

Should fix Cheapino issue 17 (https://github.com/tompi/cheapino/issues/17)

### CODE REVIEW

**Comment by tompi** [comment]
Thank you so much! Mirrored PCBs is REALLY difficult to get right... I thought I had it, but obviously not....

Anyway, I merged your fixes and sorted out the encoder action.
I also think some of your mappings were slightly off.

Im typing this now on my latest commit, seems to be working really well.

I deleted all of the hacks to avoid ghosting and encoder with entire rows, all of the hw problemes seems to be gone now!

I will rename the keyboard to cheapinov2 I think and merge to the cheapino branch

**Comment by fauh45** [comment]
Huh in my build your mapping doesn't really work. Not sure how it could be different? But yep, as the result goes, no more ghosting and encoder issues anymore! Thanks for the design!

**Comment by tompi** [comment]
Did you use a custom keymap ? The keymap is essentially another level of
mapping.

Could you try flashing the default or miryoku nd see if it works?

**Comment by fauh45** [comment]
Sorry for just got back on this, but yea, using your current mapping it results in row to col, and col to row being reversed, e.g. the leftmost col now is the thumb cluster, while the thumb cluster is the QAZ (on default keymaps). I don't think there's any changes done to the schematic before I order the PCB right? And I don't think there's any change in matrix.c either...

**Comment by tompi** [comment]
Just have to check, you sure you didnt solder the diodes in reverse
position? I think I mentioned the pcb ordered in the commit message, its
not quite the latest…

**Comment by fauh45** [comment]
Ahhh that might be why... I soldered it cathode going right on the left side, and left on the right side. Not sure if that's the latest?

**Comment by tompi** [comment]
yeah, the footprint I chose has very weak markings :( 

Cathode should go left on left side, if you look closely there is a slightly stronger line to the left.
I think its also convention that cathode is oriented towards the square pad, not round.

Anyway, seems to be working fine, Im gonna try to design a case during the slow holiday :)
Merry christmas!

**Comment by fauh45** [comment]
Ahhh yea that's why, I did solder all the cathode against the thicker stripe. I was referencing the PCB design and it does told me to do it that way though? But yea, one input I could say is to maybe make the thicker, and be on both of the side instead of just the top one.

And didn't know there was a convection on square and round holes there, new things learned!

As for case... Not really my forte haha. Happy holidays to you too!

**Pull request merged**
